### ISSUE TITLE
Failed to build in Xcode 16.0 Beta

### ISSUE THREAD

**Issue by kapitoshka438** [appmetrica/appmetrica-sdk-ios#17]
### 📚 AppMetrica SDK Version

5.4.0

### 🛠️ Xcode Version

Version 16.0 beta (16A5171c)

### 📱 Device Information

iPhone 15 Pro (18.0)

### ⚙️ Installation Method

Swift Package Manager

### 📝 Description

```
AMASearchAdsRequester.m:5:9: error: 'iAd/ADClient.h' file not found (in target 'AppMetricaCore' from project 'AppMetrica')
    note: Did not find header 'ADClient.h' in framework 'iAd' (loaded from '/Applications/Xcode-16.0.0-Beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.0.sdk/System/Library/Frameworks')
```
<img width="904" alt="Снимок экрана 2024-06-11 в 17 08 45" src="https://github.com/appmetrica/appmetrica-sdk-ios/assets/3232401/a6829852-f204-4057-bc7f-ab1b7ee2ea58">

### 📋 Relevant AppMetrica Log Output or Crash Logs

<details>
<summary>Expand to view logs</summary>
<br>

```
// Your logs go here
```

</details>

### 📦 Attach Package.resolved (Swift Package Manager Users)

<details>
<summary>Click to expand <code>Package.resolved</code></summary>
<br>

```json
// Replace with your Package.resolved contents
```

</details>

### 🍫 Attach Podfile.lock (CocoaPods Users)

<details>
<summary>Click to expand <code>Podfile.lock</code></summary>
<br>

```ruby
// Replace with your Podfile.lock contents
```

</details>

**Comment by mapmelad** [comment]
Are there any updates on this issue?
