### ISSUE TITLE
Appmetrika 5.8.0 Failed to build in Xcode 16.0

### ISSUE THREAD

**Issue by albertolobohasten** [appmetrica/appmetrica-sdk-ios#23]
### 📚 AppMetrica SDK Version

5.8.0

### 🛠️ Xcode Version

Version 16.0 (16A242d)

### 📱 Device Information

iOS 17, iOS18

### ⚙️ Installation Method

CocoaPods

### 📝 Description

The appmetrika SDK need to update to the new release of KCrash 2.0.0-rc.2. In Xcode 16 we have this bug:
- Use of undeclared identifier INT_MAX in KCrash 2.0.0-rc.1

The fix is here:
- https://github.com/kstenerud/KSCrash/issues/566

### 📋 Relevant AppMetrica Log Output or Crash Logs

<details>
<summary>Expand to view logs</summary>
<br>

```
// Your logs go here
```

</details>

### 📦 Attach Package.resolved (Swift Package Manager Users)

<details>
<summary>Click to expand <code>Package.resolved</code></summary>
<br>

```json
// Replace with your Package.resolved contents
```

</details>

### 🍫 Attach Podfile.lock (CocoaPods Users)

<details>
<summary>Click to expand <code>Podfile.lock</code></summary>
<br>

```ruby
// Replace with your Podfile.lock contents
```
  - AppMetricaAdSupport (5.8.0):
    - AppMetricaCore (= 5.8.0)
    - AppMetricaCoreExtension (= 5.8.0)
  - AppMetricaAnalytics (5.8.0):
    - AppMetricaAdSupport (= 5.8.0)
    - AppMetricaCore (= 5.8.0)
    - AppMetricaCrashes (= 5.8.0)
    - AppMetricaWebKit (= 5.8.0)
  - AppMetricaCore (5.8.0):
    - AppMetricaCoreUtils (= 5.8.0)
    - AppMetricaEncodingUtils (= 5.8.0)
    - AppMetricaFMDB (= 5.8.0)
    - AppMetricaHostState (= 5.8.0)
    - AppMetricaLog (= 5.8.0)
    - AppMetricaNetwork (= 5.8.0)
    - AppMetricaPlatform (= 5.8.0)
    - AppMetricaProtobuf (= 5.8.0)
    - AppMetricaProtobufUtils (= 5.8.0)
    - AppMetricaStorageUtils (= 5.8.0)
  - AppMetricaCoreExtension (5.8.0):
    - AppMetricaCore (= 5.8.0)
    - AppMetricaStorageUtils (= 5.8.0)
  - AppMetricaCoreUtils (5.8.0):
    - AppMetricaLog (= 5.8.0)
  - AppMetricaCrashes (5.8.0):
    - AppMetricaCore (= 5.8.0)
    - AppMetricaCoreExtension (= 5.8.0)
    - AppMetricaCoreUtils (= 5.8.0)
    - AppMetricaEncodingUtils (= 5.8.0)
    - AppMetricaHostState (= 5.8.0)
    - AppMetricaLog (= 5.8.0)
    - AppMetricaPlatform (= 5.8.0)
    - AppMetricaProtobufUtils (= 5.8.0)
    - AppMetricaStorageUtils (= 5.8.0)
    - KSCrash/Recording (< 2.1.0, >= 2.0.0-rc.1)
  - AppMetricaEncodingUtils (5.8.0):
    - AppMetricaCoreUtils (= 5.8.0)
    - AppMetricaLog (= 5.8.0)
    - AppMetricaPlatform (= 5.8.0)
  - AppMetricaFMDB (5.8.0)
  - AppMetricaHostState (5.8.0):
    - AppMetricaCoreUtils (= 5.8.0)
    - AppMetricaLog (= 5.8.0)
  - AppMetricaLog (5.8.0)
  - AppMetricaNetwork (5.8.0):
    - AppMetricaCoreUtils (= 5.8.0)
    - AppMetricaLog (= 5.8.0)
    - AppMetricaPlatform (= 5.8.0)
  - AppMetricaPlatform (5.8.0):
    - AppMetricaCoreUtils (= 5.8.0)
    - AppMetricaLog (= 5.8.0)
  - AppMetricaProtobuf (5.8.0)
  - AppMetricaProtobufUtils (5.8.0):
    - AppMetricaProtobuf (= 5.8.0)
  - AppMetricaStorageUtils (5.8.0):
    - AppMetricaCoreUtils (= 5.8.0)
    - AppMetricaLog (= 5.8.0)
  - AppMetricaWebKit (5.8.0):
    - AppMetricaCore (= 5.8.0)
    - AppMetricaCoreUtils (= 5.8.0)
    - AppMetricaLog (= 5.8.0)
  - KSCrash/Core (2.0.0-rc.1)
  - KSCrash/Recording (2.0.0-rc.1):
    - KSCrash/RecordingCore
  - KSCrash/RecordingCore (2.0.0-rc.1):
    - KSCrash/Core
</details>

**Comment by Andrez092** [comment]
This might help:This file might fix it
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive

**Comment by alexklints** [comment]
Hello!
Thank 
We limit the dependency on KSCrash to the major version. Try updating or reinstalling pods. We will bring up the latest version of KSCrash with the next update.

**Comment by Sergey70** [comment]
Resolved and available starting from version `2.0.0-rc.2` of KSCrash.
